### ISSUE TITLE
Community co-creation approach for NSF 5G PAWR proposal

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/smartcityroadmap#40]
**Trello board for community engagement actions: https://trello.com/b/bbjJceFn/austin-nsf-pawr-grant-community-engagement**

Scope: https://docs.google.com/document/d/11aGhXHqwZLX7FD1TYq_2GOX-I9VCen6B2J2oWTX9CTc/edit#

## task list
- [x] Talk with Rey about letter of support from CM. Cover memo + draft letter
- [x] Draft budget for community benefits/engagement
- [x] Action plan for community outreach
