### ISSUE TITLE
Plan for researching departments' emerging tech roadmaps

### ISSUE THREAD

**Issue by danielhonker** [cityofaustin/smartcityroadmap#58]
### Context
CTO wants insight on how other departments are exploring/investing in emerging tech areas. This will inform priorities and focus areas for the CTO organization.

## Desired outcome
Understanding of other departments' interests and investment in emerging tech areas, as input to CTO org's work in emerging tech

Need to know: 
- Opportunities for shared platforms
- Insights for CTO emerging tech roadmap
- High priority exploration areas, based on other departments' interest and investment

Ask about:
- What stage their activity is in
- What investment they have made so far
- What partners they are working with
- Key use cases and interests in the tech
- Challenges

## Tasks

- [x] Scope this out, with timeline and needs for resourcing - before 3/6/20
- [x] Create interview guide - before 3/12/20 -- **Complete - [interview guide here](https://docs.google.com/document/d/1DIEtB_ZNeslitems4BSqkWzpxsY_J8NmdxmxBjchhFY/edit#heading=h.9x5a6s5epjwb)**
- [x] Reach out to AE, AWU, ATD to schedule interviews - reach out by 3/6/20
- Get all the interviews scheduled -- by 3/12/20
  - [ ] AE // ~~Apr 3~~ **Will reschedule for after COVID**
  - [x] ATD // Apr 1
  - [ ] AWU // TBD
  - [x] Fleet // April 6

## Separate issues for interviews with Departments

AE #63 
AWU #60 
ATD #61 
Fleet #62
